import React, { useCallback } from 'react';
import { Pressable, StyleSheet, Text, Vibration, View } from 'react-native';

import { useSettingsStore } from '../store/settingsStore';
import { colors, space, type as typography } from '../theme';

/** Digit plus the letters printed under it on a real handset. */
const KEYS: { digit: string; letters?: string }[] = [
  { digit: '1' },
  { digit: '2', letters: 'ABC' },
  { digit: '3', letters: 'DEF' },
  { digit: '4', letters: 'GHI' },
  { digit: '5', letters: 'JKL' },
  { digit: '6', letters: 'MNO' },
  { digit: '7', letters: 'PQRS' },
  { digit: '8', letters: 'TUV' },
  { digit: '9', letters: 'WXYZ' },
  { digit: '*' },
  { digit: '0', letters: '+' },
  { digit: '#' },
];

interface DialpadProps {
  onPress: (digit: string) => void;
  /** Long-pressing "0" types "+"; long-pressing "1" can reach voicemail. */
  onLongPress?: (digit: string) => void;
  compact?: boolean;
}

export function Dialpad({
  onPress,
  onLongPress,
  compact = false,
}: DialpadProps) {
  const feedback = useSettingsStore(state => state.dialpadTones);

  const handlePress = useCallback(
    (digit: string) => {
      if (feedback) {
        // A short haptic stands in for the DTMF click; the tone itself is
        // generated by the SIP layer during a call.
        Vibration.vibrate(10);
      }
      onPress(digit);
    },
    [onPress, feedback],
  );

  const size = compact ? 56 : 68;

  return (
    <View style={[styles.grid, compact && styles.gridCompact]}>
      {KEYS.map(({ digit, letters }) => (
        <Pressable
          key={digit}
          onPress={() => handlePress(digit)}
          onLongPress={() => onLongPress?.(digit)}
          style={({ pressed }) => [
            styles.key,
            {
              width: size,
              height: size,
              borderRadius: size / 2,
              backgroundColor: pressed ? colors.surface3 : colors.surface,
              borderColor: pressed ? colors.borderStrong : colors.border,
            },
          ]}
          accessibilityRole="button"
          accessibilityLabel={`Dial ${digit}`}
        >
          <Text style={[styles.digit, compact && styles.digitCompact]}>
            {digit}
          </Text>
          {letters ? <Text style={styles.letters}>{letters}</Text> : null}
        </Pressable>
      ))}
    </View>
  );
}

const styles = StyleSheet.create({
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    maxWidth: 288,
    alignSelf: 'center',
    gap: space.lg,
  },
  gridCompact: { maxWidth: 240, gap: space.md },
  key: {
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: StyleSheet.hairlineWidth,
  },
  digit: { fontSize: 26, fontWeight: '400', color: colors.text },
  digitCompact: { fontSize: 22 },
  letters: {
    ...typography.micro,
    fontSize: 9,
    letterSpacing: 1,
    marginTop: 1,
  },
});
